spring.application.name=manatandas-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/manatandas
spring.datasource.username=heesukim
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true